/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import Bombe from "../../operations/Bombe.js";
import Colossus from "../../operations/Colossus.js";
import Enigma from "../../operations/Enigma.js";
import Lorenz from "../../operations/Lorenz.js";
import MultipleBombe from "../../operations/MultipleBombe.js";
import SIGABA from "../../operations/SIGABA.js";
import Typex from "../../operations/Typex.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Bletchley = {
    "Bombe": Bombe,
    "Colossus": Colossus,
    "Enigma": Enigma,
    "Lorenz": Lorenz,
    "Multiple Bombe": MultipleBombe,
    "SIGABA": SIGABA,
    "Typex": Typex,
};

export default OpModules;
