/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import Entropy from "../../operations/Entropy.js";
import HeatmapChart from "../../operations/HeatmapChart.js";
import HexDensityChart from "../../operations/HexDensityChart.js";
import ScatterChart from "../../operations/ScatterChart.js";
import SeriesChart from "../../operations/SeriesChart.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Charts = {
    "Entropy": Entropy,
    "Heatmap chart": HeatmapChart,
    "Hex Density chart": HexDensityChart,
    "Scatter chart": ScatterChart,
    "Series chart": SeriesChart,
};

export default OpModules;
