/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import A1Z26CipherDecode from "../../operations/A1Z26CipherDecode.js";
import A1Z26CipherEncode from "../../operations/A1Z26CipherEncode.js";
import AESDecrypt from "../../operations/AESDecrypt.js";
import AESEncrypt from "../../operations/AESEncrypt.js";
import AESKeyUnwrap from "../../operations/AESKeyUnwrap.js";
import AESKeyWrap from "../../operations/AESKeyWrap.js";
import AffineCipherDecode from "../../operations/AffineCipherDecode.js";
import AffineCipherEncode from "../../operations/AffineCipherEncode.js";
import AtbashCipher from "../../operations/AtbashCipher.js";
import BifidCipherDecode from "../../operations/BifidCipherDecode.js";
import BifidCipherEncode from "../../operations/BifidCipherEncode.js";
import BlowfishDecrypt from "../../operations/BlowfishDecrypt.js";
import BlowfishEncrypt from "../../operations/BlowfishEncrypt.js";
import CaesarBoxCipher from "../../operations/CaesarBoxCipher.js";
import CetaceanCipherDecode from "../../operations/CetaceanCipherDecode.js";
import CetaceanCipherEncode from "../../operations/CetaceanCipherEncode.js";
import ChaCha from "../../operations/ChaCha.js";
import DESDecrypt from "../../operations/DESDecrypt.js";
import DESEncrypt from "../../operations/DESEncrypt.js";
import DeriveEVPKey from "../../operations/DeriveEVPKey.js";
import DerivePBKDF2Key from "../../operations/DerivePBKDF2Key.js";
import ECDSASign from "../../operations/ECDSASign.js";
import ECDSASignatureConversion from "../../operations/ECDSASignatureConversion.js";
import ECDSAVerify from "../../operations/ECDSAVerify.js";
import GOSTDecrypt from "../../operations/GOSTDecrypt.js";
import GOSTEncrypt from "../../operations/GOSTEncrypt.js";
import GOSTKeyUnwrap from "../../operations/GOSTKeyUnwrap.js";
import GOSTKeyWrap from "../../operations/GOSTKeyWrap.js";
import GOSTSign from "../../operations/GOSTSign.js";
import GOSTVerify from "../../operations/GOSTVerify.js";
import GenerateECDSAKeyPair from "../../operations/GenerateECDSAKeyPair.js";
import GenerateRSAKeyPair from "../../operations/GenerateRSAKeyPair.js";
import PseudoRandomNumberGenerator from "../../operations/PseudoRandomNumberGenerator.js";
import RC2Decrypt from "../../operations/RC2Decrypt.js";
import RC2Encrypt from "../../operations/RC2Encrypt.js";
import RC4 from "../../operations/RC4.js";
import RC4Drop from "../../operations/RC4Drop.js";
import RSADecrypt from "../../operations/RSADecrypt.js";
import RSAEncrypt from "../../operations/RSAEncrypt.js";
import RSASign from "../../operations/RSASign.js";
import RSAVerify from "../../operations/RSAVerify.js";
import Rabbit from "../../operations/Rabbit.js";
import RailFenceCipherDecode from "../../operations/RailFenceCipherDecode.js";
import RailFenceCipherEncode from "../../operations/RailFenceCipherEncode.js";
import SM4Decrypt from "../../operations/SM4Decrypt.js";
import SM4Encrypt from "../../operations/SM4Encrypt.js";
import Salsa20 from "../../operations/Salsa20.js";
import TripleDESDecrypt from "../../operations/TripleDESDecrypt.js";
import TripleDESEncrypt from "../../operations/TripleDESEncrypt.js";
import VigenèreDecode from "../../operations/VigenèreDecode.js";
import VigenèreEncode from "../../operations/VigenèreEncode.js";
import XSalsa20 from "../../operations/XSalsa20.js";
import XXTEADecrypt from "../../operations/XXTEADecrypt.js";
import XXTEAEncrypt from "../../operations/XXTEAEncrypt.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Ciphers = {
    "A1Z26 Cipher Decode": A1Z26CipherDecode,
    "A1Z26 Cipher Encode": A1Z26CipherEncode,
    "AES Decrypt": AESDecrypt,
    "AES Encrypt": AESEncrypt,
    "AES Key Unwrap": AESKeyUnwrap,
    "AES Key Wrap": AESKeyWrap,
    "Affine Cipher Decode": AffineCipherDecode,
    "Affine Cipher Encode": AffineCipherEncode,
    "Atbash Cipher": AtbashCipher,
    "Bifid Cipher Decode": BifidCipherDecode,
    "Bifid Cipher Encode": BifidCipherEncode,
    "Blowfish Decrypt": BlowfishDecrypt,
    "Blowfish Encrypt": BlowfishEncrypt,
    "Caesar Box Cipher": CaesarBoxCipher,
    "Cetacean Cipher Decode": CetaceanCipherDecode,
    "Cetacean Cipher Encode": CetaceanCipherEncode,
    "ChaCha": ChaCha,
    "DES Decrypt": DESDecrypt,
    "DES Encrypt": DESEncrypt,
    "Derive EVP key": DeriveEVPKey,
    "Derive PBKDF2 key": DerivePBKDF2Key,
    "ECDSA Sign": ECDSASign,
    "ECDSA Signature Conversion": ECDSASignatureConversion,
    "ECDSA Verify": ECDSAVerify,
    "GOST Decrypt": GOSTDecrypt,
    "GOST Encrypt": GOSTEncrypt,
    "GOST Key Unwrap": GOSTKeyUnwrap,
    "GOST Key Wrap": GOSTKeyWrap,
    "GOST Sign": GOSTSign,
    "GOST Verify": GOSTVerify,
    "Generate ECDSA Key Pair": GenerateECDSAKeyPair,
    "Generate RSA Key Pair": GenerateRSAKeyPair,
    "Pseudo-Random Number Generator": PseudoRandomNumberGenerator,
    "RC2 Decrypt": RC2Decrypt,
    "RC2 Encrypt": RC2Encrypt,
    "RC4": RC4,
    "RC4 Drop": RC4Drop,
    "RSA Decrypt": RSADecrypt,
    "RSA Encrypt": RSAEncrypt,
    "RSA Sign": RSASign,
    "RSA Verify": RSAVerify,
    "Rabbit": Rabbit,
    "Rail Fence Cipher Decode": RailFenceCipherDecode,
    "Rail Fence Cipher Encode": RailFenceCipherEncode,
    "SM4 Decrypt": SM4Decrypt,
    "SM4 Encrypt": SM4Encrypt,
    "Salsa20": Salsa20,
    "Triple DES Decrypt": TripleDESDecrypt,
    "Triple DES Encrypt": TripleDESEncrypt,
    "Vigenère Decode": VigenèreDecode,
    "Vigenère Encode": VigenèreEncode,
    "XSalsa20": XSalsa20,
    "XXTEA Decrypt": XXTEADecrypt,
    "XXTEA Encrypt": XXTEAEncrypt,
};

export default OpModules;
