/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import CSSBeautify from "../../operations/CSSBeautify.js";
import CSSMinify from "../../operations/CSSMinify.js";
import CSSSelector from "../../operations/CSSSelector.js";
import FromMessagePack from "../../operations/FromMessagePack.js";
import GenericCodeBeautify from "../../operations/GenericCodeBeautify.js";
import JPathExpression from "../../operations/JPathExpression.js";
import JSONBeautify from "../../operations/JSONBeautify.js";
import JSONMinify from "../../operations/JSONMinify.js";
import JavaScriptBeautify from "../../operations/JavaScriptBeautify.js";
import JavaScriptMinify from "../../operations/JavaScriptMinify.js";
import JavaScriptParser from "../../operations/JavaScriptParser.js";
import RenderMarkdown from "../../operations/RenderMarkdown.js";
import SQLBeautify from "../../operations/SQLBeautify.js";
import SQLMinify from "../../operations/SQLMinify.js";
import SyntaxHighlighter from "../../operations/SyntaxHighlighter.js";
import ToCamelCase from "../../operations/ToCamelCase.js";
import ToKebabCase from "../../operations/ToKebabCase.js";
import ToMessagePack from "../../operations/ToMessagePack.js";
import ToSnakeCase from "../../operations/ToSnakeCase.js";
import XMLBeautify from "../../operations/XMLBeautify.js";
import XMLMinify from "../../operations/XMLMinify.js";
import XPathExpression from "../../operations/XPathExpression.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Code = {
    "CSS Beautify": CSSBeautify,
    "CSS Minify": CSSMinify,
    "CSS selector": CSSSelector,
    "From MessagePack": FromMessagePack,
    "Generic Code Beautify": GenericCodeBeautify,
    "JPath expression": JPathExpression,
    "JSON Beautify": JSONBeautify,
    "JSON Minify": JSONMinify,
    "JavaScript Beautify": JavaScriptBeautify,
    "JavaScript Minify": JavaScriptMinify,
    "JavaScript Parser": JavaScriptParser,
    "Render Markdown": RenderMarkdown,
    "SQL Beautify": SQLBeautify,
    "SQL Minify": SQLMinify,
    "Syntax highlighter": SyntaxHighlighter,
    "To Camel case": ToCamelCase,
    "To Kebab case": ToKebabCase,
    "To MessagePack": ToMessagePack,
    "To Snake case": ToSnakeCase,
    "XML Beautify": XMLBeautify,
    "XML Minify": XMLMinify,
    "XPath expression": XPathExpression,
};

export default OpModules;
