/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import Bzip2Compress from "../../operations/Bzip2Compress.js";
import Bzip2Decompress from "../../operations/Bzip2Decompress.js";
import Gunzip from "../../operations/Gunzip.js";
import Gzip from "../../operations/Gzip.js";
import LZ4Compress from "../../operations/LZ4Compress.js";
import LZ4Decompress from "../../operations/LZ4Decompress.js";
import LZMACompress from "../../operations/LZMACompress.js";
import LZMADecompress from "../../operations/LZMADecompress.js";
import LZNT1Decompress from "../../operations/LZNT1Decompress.js";
import LZStringCompress from "../../operations/LZStringCompress.js";
import LZStringDecompress from "../../operations/LZStringDecompress.js";
import RawDeflate from "../../operations/RawDeflate.js";
import RawInflate from "../../operations/RawInflate.js";
import Tar from "../../operations/Tar.js";
import Untar from "../../operations/Untar.js";
import Unzip from "../../operations/Unzip.js";
import Zip from "../../operations/Zip.js";
import ZlibDeflate from "../../operations/ZlibDeflate.js";
import ZlibInflate from "../../operations/ZlibInflate.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Compression = {
    "Bzip2 Compress": Bzip2Compress,
    "Bzip2 Decompress": Bzip2Decompress,
    "Gunzip": Gunzip,
    "Gzip": Gzip,
    "LZ4 Compress": LZ4Compress,
    "LZ4 Decompress": LZ4Decompress,
    "LZMA Compress": LZMACompress,
    "LZMA Decompress": LZMADecompress,
    "LZNT1 Decompress": LZNT1Decompress,
    "LZString Compress": LZStringCompress,
    "LZString Decompress": LZStringDecompress,
    "Raw Deflate": RawDeflate,
    "Raw Inflate": RawInflate,
    "Tar": Tar,
    "Untar": Untar,
    "Unzip": Unzip,
    "Zip": Zip,
    "Zlib Deflate": ZlibDeflate,
    "Zlib Inflate": ZlibInflate,
};

export default OpModules;
