/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import Adler32Checksum from "../../operations/Adler32Checksum.js";
import AnalyseHash from "../../operations/AnalyseHash.js";
import Argon2 from "../../operations/Argon2.js";
import Argon2Compare from "../../operations/Argon2Compare.js";
import Bcrypt from "../../operations/Bcrypt.js";
import BcryptCompare from "../../operations/BcryptCompare.js";
import BcryptParse from "../../operations/BcryptParse.js";
import CMAC from "../../operations/CMAC.js";
import CTPH from "../../operations/CTPHH.js";
import CipherSaber2Decrypt from "../../operations/CipherSaber2Decrypt.js";
import CipherSaber2Encrypt from "../../operations/CipherSaber2Encrypt.js";
import CompareCTPHHashes from "../../operations/CompareCTPHHashes.js";
import CompareSSDEEPHashes from "../../operations/CompareSSDEEPHashes.js";
import DeriveHKDFKey from "../../operations/DeriveHKDFKey.js";
import Fletcher16Checksum from "../../operations/Fletcher16Checksum.js";
import Fletcher32Checksum from "../../operations/Fletcher32Checksum.js";
import Fletcher64Checksum from "../../operations/Fletcher64Checksum.js";
import Fletcher8Checksum from "../../operations/Fletcher8Checksum.js";
import GenerateAllHashes from "../../operations/GenerateAllHashes.js";
import GenerateUUID from "../../operations/GenerateUUID.js";
import HAS160 from "../../operations/HAS160.js";
import HASSHClientFingerprint from "../../operations/HASSHClientFingerprint.js";
import HASSHServerFingerprint from "../../operations/HASSHServerFingerprint.js";
import HMAC from "../../operations/HMAC.js";
import JA3Fingerprint from "../../operations/JA3Fingerprint.js";
import JA3SFingerprint from "../../operations/JA3SFingerprint.js";
import JA4Fingerprint from "../../operations/JA4Fingerprint.js";
import JA4ServerFingerprint from "../../operations/JA4ServerFingerprint.js";
import JWTDecode from "../../operations/JWTDecode.js";
import JWTSign from "../../operations/JWTSign.js";
import JWTVerify from "../../operations/JWTVerify.js";
import Keccak from "../../operations/Keccak.js";
import LMHash from "../../operations/LMHash.js";
import LS47Decrypt from "../../operations/LS47Decrypt.js";
import LS47Encrypt from "../../operations/LS47Encrypt.js";
import MD2 from "../../operations/MD2.js";
import MD4 from "../../operations/MD4.js";
import MD5 from "../../operations/MD5.js";
import MD6 from "../../operations/MD6.js";
import NTHash from "../../operations/NTHash.js";
import RIPEMD from "../../operations/RIPEMD.js";
import SHA0 from "../../operations/SHA0.js";
import SHA1 from "../../operations/SHA1.js";
import SHA2 from "../../operations/SHA2.js";
import SHA3 from "../../operations/SHA3.js";
import SM2Decrypt from "../../operations/SM2Decrypt.js";
import SM2Encrypt from "../../operations/SM2Encrypt.js";
import SM3 from "../../operations/SM3.js";
import SSDEEP from "../../operations/SSDEEEP.js";
import Scrypt from "../../operations/Scrypt.js";
import Shake from "../../operations/Shake.js";
import Snefru from "../../operations/Snefru.js";
import TCPIPChecksum from "../../operations/TCPIPChecksum.js";
import Whirlpool from "../../operations/Whirlpool.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Crypto = {
    "Adler-32 Checksum": Adler32Checksum,
    "Analyse hash": AnalyseHash,
    "Argon2": Argon2,
    "Argon2 compare": Argon2Compare,
    "Bcrypt": Bcrypt,
    "Bcrypt compare": BcryptCompare,
    "Bcrypt parse": BcryptParse,
    "CMAC": CMAC,
    "CTPH": CTPH,
    "CipherSaber2 Decrypt": CipherSaber2Decrypt,
    "CipherSaber2 Encrypt": CipherSaber2Encrypt,
    "Compare CTPH hashes": CompareCTPHHashes,
    "Compare SSDEEP hashes": CompareSSDEEPHashes,
    "Derive HKDF key": DeriveHKDFKey,
    "Fletcher-16 Checksum": Fletcher16Checksum,
    "Fletcher-32 Checksum": Fletcher32Checksum,
    "Fletcher-64 Checksum": Fletcher64Checksum,
    "Fletcher-8 Checksum": Fletcher8Checksum,
    "Generate all hashes": GenerateAllHashes,
    "Generate UUID": GenerateUUID,
    "HAS-160": HAS160,
    "HASSH Client Fingerprint": HASSHClientFingerprint,
    "HASSH Server Fingerprint": HASSHServerFingerprint,
    "HMAC": HMAC,
    "JA3 Fingerprint": JA3Fingerprint,
    "JA3S Fingerprint": JA3SFingerprint,
    "JA4 Fingerprint": JA4Fingerprint,
    "JA4Server Fingerprint": JA4ServerFingerprint,
    "JWT Decode": JWTDecode,
    "JWT Sign": JWTSign,
    "JWT Verify": JWTVerify,
    "Keccak": Keccak,
    "LM Hash": LMHash,
    "LS47 Decrypt": LS47Decrypt,
    "LS47 Encrypt": LS47Encrypt,
    "MD2": MD2,
    "MD4": MD4,
    "MD5": MD5,
    "MD6": MD6,
    "NT Hash": NTHash,
    "RIPEMD": RIPEMD,
    "SHA0": SHA0,
    "SHA1": SHA1,
    "SHA2": SHA2,
    "SHA3": SHA3,
    "SM2 Decrypt": SM2Decrypt,
    "SM2 Encrypt": SM2Encrypt,
    "SM3": SM3,
    "SSDEEP": SSDEEP,
    "Scrypt": Scrypt,
    "Shake": Shake,
    "Snefru": Snefru,
    "TCP/IP Checksum": TCPIPChecksum,
    "Whirlpool": Whirlpool,
};

export default OpModules;
