/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import ADD from "../../operations/ADD.js";
import AND from "../../operations/AND.js";
import AddLineNumbers from "../../operations/AddLineNumbers.js";
import BaconCipherDecode from "../../operations/BaconCipherDecode.js";
import BaconCipherEncode from "../../operations/BaconCipherEncode.js";
import BitShiftLeft from "../../operations/BitShiftLeft.js";
import BitShiftRight from "../../operations/BitShiftRight.js";
import CRCChecksum from "../../operations/CRCChecksum.js";
import CSVToJSON from "../../operations/CSVToJSON.js";
import CaretMdecode from "../../operations/CaretMdecode.js";
import CartesianProduct from "../../operations/CartesianProduct.js";
import ChangeIPFormat from "../../operations/ChangeIPFormat.js";
import ChiSquare from "../../operations/ChiSquare.js";
import Comment from "../../operations/Comment.js";
import ConditionalJump from "../../operations/ConditionalJump.js";
import ConvertArea from "../../operations/ConvertArea.js";
import ConvertDataUnits from "../../operations/ConvertDataUnits.js";
import ConvertDistance from "../../operations/ConvertDistance.js";
import ConvertLeetSpeak from "../../operations/ConvertLeetSpeak.js";
import ConvertMass from "../../operations/ConvertMass.js";
import ConvertSpeed from "../../operations/ConvertSpeed.js";
import ConvertToNATOAlphabet from "../../operations/ConvertToNATOAlphabet.js";
import CountOccurrences from "../../operations/CountOccurrences.js";
import DNSOverHTTPS from "../../operations/DNSOverHTTPS.js";
import DateTimeDelta from "../../operations/DateTimeDelta.js";
import DechunkHTTPResponse from "../../operations/DechunkHTTPResponse.js";
import DecodeNetBIOSName from "../../operations/DecodeNetBIOSName.js";
import DefangIPAddresses from "../../operations/DefangIPAddresses.js";
import DefangURL from "../../operations/DefangURL.js";
import DetectFileType from "../../operations/DetectFileType.js";
import Divide from "../../operations/Divide.js";
import DropBytes from "../../operations/DropBytes.js";
import DropNthBytes from "../../operations/DropNthBytes.js";
import ELFInfo from "../../operations/ELFInfo.js";
import EncodeNetBIOSName from "../../operations/EncodeNetBIOSName.js";
import EscapeString from "../../operations/EscapeString.js";
import EscapeUnicodeCharacters from "../../operations/EscapeUnicodeCharacters.js";
import ExpandAlphabetRange from "../../operations/ExpandAlphabetRange.js";
import ExtractFiles from "../../operations/ExtractFiles.js";
import ExtractID3 from "../../operations/ExtractID3.js";
import FangURL from "../../operations/FangURL.js";
import FernetDecrypt from "../../operations/FernetDecrypt.js";
import FernetEncrypt from "../../operations/FernetEncrypt.js";
import FileTree from "../../operations/FileTree.js";
import Fork from "../../operations/Fork.js";
import FormatMACAddresses from "../../operations/FormatMACAddresses.js";
import FrequencyDistribution from "../../operations/FrequencyDistribution.js";
import FromBCD from "../../operations/FromBCD.js";
import FromBase from "../../operations/FromBase.js";
import FromBase32 from "../../operations/FromBase32.js";
import FromBase45 from "../../operations/FromBase45.js";
import FromBase58 from "../../operations/FromBase58.js";
import FromBase62 from "../../operations/FromBase62.js";
import FromBase64 from "../../operations/FromBase64.js";
import FromBase85 from "../../operations/FromBase85.js";
import FromBase92 from "../../operations/FromBase92.js";
import FromBinary from "../../operations/FromBinary.js";
import FromBraille from "../../operations/FromBraille.js";
import FromCaseInsensitiveRegex from "../../operations/FromCaseInsensitiveRegex.js";
import FromCharcode from "../../operations/FromCharcode.js";
import FromDecimal from "../../operations/FromDecimal.js";
import FromFloat from "../../operations/FromFloat.js";
import FromHex from "../../operations/FromHex.js";
import FromHexContent from "../../operations/FromHexContent.js";
import FromHexdump from "../../operations/FromHexdump.js";
import FromModhex from "../../operations/FromModhex.js";
import FromMorseCode from "../../operations/FromMorseCode.js";
import FromOctal from "../../operations/FromOctal.js";
import FromQuotedPrintable from "../../operations/FromQuotedPrintable.js";
import FromUNIXTimestamp from "../../operations/FromUNIXTimestamp.js";
import FuzzyMatch from "../../operations/FuzzyMatch.js";
import GenerateDeBruijnSequence from "../../operations/GenerateDeBruijnSequence.js";
import GenerateHOTP from "../../operations/GenerateHOTP.js";
import GenerateLoremIpsum from "../../operations/GenerateLoremIpsum.js";
import GenerateTOTP from "../../operations/GenerateTOTP.js";
import GetAllCasings from "../../operations/GetAllCasings.js";
import GetTime from "../../operations/GetTime.js";
import GroupIPAddresses from "../../operations/GroupIPAddresses.js";
import HTMLToText from "../../operations/HTMLToText.js";
import HTTPRequest from "../../operations/HTTPRequest.js";
import HammingDistance from "../../operations/HammingDistance.js";
import HaversineDistance from "../../operations/HaversineDistance.js";
import Head from "../../operations/Head.js";
import IPv6TransitionAddresses from "../../operations/IPv6TransitionAddresses.js";
import IndexOfCoincidence from "../../operations/IndexOfCoincidence.js";
import JSONToCSV from "../../operations/JSONToCSV.js";
import JSONtoYAML from "../../operations/JSONtoYAML.js";
import Jump from "../../operations/Jump.js";
import Label from "../../operations/Label.js";
import LevenshteinDistance from "../../operations/LevenshteinDistance.js";
import LuhnChecksum from "../../operations/LuhnChecksum.js";
import MIMEDecoding from "../../operations/MIMEDecoding.js";
import Magic from "../../operations/Magic.js";
import Mean from "../../operations/Mean.js";
import Median from "../../operations/Median.js";
import Merge from "../../operations/Merge.js";
import MicrosoftScriptDecoder from "../../operations/MicrosoftScriptDecoder.js";
import Multiply from "../../operations/Multiply.js";
import NOT from "../../operations/NOT.js";
import Numberwang from "../../operations/Numberwang.js";
import OR from "../../operations/OR.js";
import OffsetChecker from "../../operations/OffsetChecker.js";
import PEMToHex from "../../operations/PEMToHex.js";
import PHPDeserialize from "../../operations/PHPDeserialize.js";
import PHPSerialize from "../../operations/PHPSerialize.js";
import PLISTViewer from "../../operations/PLISTViewer.js";
import PadLines from "../../operations/PadLines.js";
import ParseColourCode from "../../operations/ParseColourCode.js";
import ParseDateTime from "../../operations/ParseDateTime.js";
import ParseIPRange from "../../operations/ParseIPRange.js";
import ParseIPv4Header from "../../operations/ParseIPv4Header.js";
import ParseIPv6Address from "../../operations/ParseIPv6Address.js";
import ParseSSHHostKey from "../../operations/ParseSSHHostKey.js";
import ParseTCP from "../../operations/ParseTCP.js";
import ParseTLSRecord from "../../operations/ParseTLSRecord.js";
import ParseTLV from "../../operations/ParseTLV.js";
import ParseUDP from "../../operations/ParseUDP.js";
import ParseUNIXFilePermissions from "../../operations/ParseUNIXFilePermissions.js";
import PlayMedia from "../../operations/PlayMedia.js";
import PowerSet from "../../operations/PowerSet.js";
import RAKE from "../../operations/RAKE.js";
import ROT13 from "../../operations/ROT13.js";
import ROT13BruteForce from "../../operations/ROT13BruteForce.js";
import ROT47 from "../../operations/ROT47.js";
import ROT47BruteForce from "../../operations/ROT47BruteForce.js";
import ROT8000 from "../../operations/ROT8000.js";
import RemoveDiacritics from "../../operations/RemoveDiacritics.js";
import RemoveLineNumbers from "../../operations/RemoveLineNumbers.js";
import RemoveNullBytes from "../../operations/RemoveNullBytes.js";
import RemoveWhitespace from "../../operations/RemoveWhitespace.js";
import Return from "../../operations/Return.js";
import Reverse from "../../operations/Reverse.js";
import RotateLeft from "../../operations/RotateLeft.js";
import RotateRight from "../../operations/RotateRight.js";
import SUB from "../../operations/SUB.js";
import ScanForEmbeddedFiles from "../../operations/ScanForEmbeddedFiles.js";
import SetDifference from "../../operations/SetDifference.js";
import SetIntersection from "../../operations/SetIntersection.js";
import SetUnion from "../../operations/SetUnion.js";
import ShowBase64Offsets from "../../operations/ShowBase64Offsets.js";
import Shuffle from "../../operations/Shuffle.js";
import Sleep from "../../operations/Sleep.js";
import Sort from "../../operations/Sort.js";
import Split from "../../operations/Split.js";
import StandardDeviation from "../../operations/StandardDeviation.js";
import StripHTMLTags from "../../operations/StripHTMLTags.js";
import StripHTTPHeaders from "../../operations/StripHTTPHeaders.js";
import StripIPv4Header from "../../operations/StripIPv4Header.js";
import StripTCPHeader from "../../operations/StripTCPHeader.js";
import StripUDPHeader from "../../operations/StripUDPHeader.js";
import Subsection from "../../operations/Subsection.js";
import Substitute from "../../operations/Substitute.js";
import Subtract from "../../operations/Subtract.js";
import Sum from "../../operations/Sum.js";
import SwapCase from "../../operations/SwapCase.js";
import SwapEndianness from "../../operations/SwapEndianness.js";
import SymmetricDifference from "../../operations/SymmetricDifference.js";
import Tail from "../../operations/Tail.js";
import TakeBytes from "../../operations/TakeBytes.js";
import TakeNthBytes from "../../operations/TakeNthBytes.js";
import ToBCD from "../../operations/ToBCD.js";
import ToBase from "../../operations/ToBase.js";
import ToBase32 from "../../operations/ToBase32.js";
import ToBase45 from "../../operations/ToBase45.js";
import ToBase58 from "../../operations/ToBase58.js";
import ToBase62 from "../../operations/ToBase62.js";
import ToBase64 from "../../operations/ToBase64.js";
import ToBase85 from "../../operations/ToBase85.js";
import ToBase92 from "../../operations/ToBase92.js";
import ToBinary from "../../operations/ToBinary.js";
import ToBraille from "../../operations/ToBraille.js";
import ToCaseInsensitiveRegex from "../../operations/ToCaseInsensitiveRegex.js";
import ToCharcode from "../../operations/ToCharcode.js";
import ToDecimal from "../../operations/ToDecimal.js";
import ToFloat from "../../operations/ToFloat.js";
import ToHex from "../../operations/ToHex.js";
import ToHexContent from "../../operations/ToHexContent.js";
import ToHexdump from "../../operations/ToHexdump.js";
import ToLowerCase from "../../operations/ToLowerCase.js";
import ToModhex from "../../operations/ToModhex.js";
import ToMorseCode from "../../operations/ToMorseCode.js";
import ToOctal from "../../operations/ToOctal.js";
import ToQuotedPrintable from "../../operations/ToQuotedPrintable.js";
import ToTable from "../../operations/ToTable.js";
import ToUNIXTimestamp from "../../operations/ToUNIXTimestamp.js";
import ToUpperCase from "../../operations/ToUpperCase.js";
import TranslateDateTimeFormat from "../../operations/TranslateDateTimeFormat.js";
import UNIXTimestampToWindowsFiletime from "../../operations/UNIXTimestampToWindowsFiletime.js";
import UnescapeString from "../../operations/UnescapeString.js";
import UnescapeUnicodeCharacters from "../../operations/UnescapeUnicodeCharacters.js";
import UnicodeTextFormat from "../../operations/UnicodeTextFormat.js";
import Unique from "../../operations/Unique.js";
import VarIntDecode from "../../operations/VarIntDecode.js";
import VarIntEncode from "../../operations/VarIntEncode.js";
import WindowsFiletimeToUNIXTimestamp from "../../operations/WindowsFiletimeToUNIXTimestamp.js";
import XKCDRandomNumber from "../../operations/XKCDRandomNumber.js";
import XOR from "../../operations/XOR.js";
import XORBruteForce from "../../operations/XORBruteForce.js";
import YAMLToJSON from "../../operations/YAMLToJSON.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Default = {
    "ADD": ADD,
    "AND": AND,
    "Add line numbers": AddLineNumbers,
    "Bacon Cipher Decode": BaconCipherDecode,
    "Bacon Cipher Encode": BaconCipherEncode,
    "Bit shift left": BitShiftLeft,
    "Bit shift right": BitShiftRight,
    "CRC Checksum": CRCChecksum,
    "CSV to JSON": CSVToJSON,
    "Caret/M-decode": CaretMdecode,
    "Cartesian Product": CartesianProduct,
    "Change IP format": ChangeIPFormat,
    "Chi Square": ChiSquare,
    "Comment": Comment,
    "Conditional Jump": ConditionalJump,
    "Convert area": ConvertArea,
    "Convert data units": ConvertDataUnits,
    "Convert distance": ConvertDistance,
    "Convert Leet Speak": ConvertLeetSpeak,
    "Convert mass": ConvertMass,
    "Convert speed": ConvertSpeed,
    "Convert to NATO alphabet": ConvertToNATOAlphabet,
    "Count occurrences": CountOccurrences,
    "DNS over HTTPS": DNSOverHTTPS,
    "DateTime Delta": DateTimeDelta,
    "Dechunk HTTP response": DechunkHTTPResponse,
    "Decode NetBIOS Name": DecodeNetBIOSName,
    "Defang IP Addresses": DefangIPAddresses,
    "Defang URL": DefangURL,
    "Detect File Type": DetectFileType,
    "Divide": Divide,
    "Drop bytes": DropBytes,
    "Drop nth bytes": DropNthBytes,
    "ELF Info": ELFInfo,
    "Encode NetBIOS Name": EncodeNetBIOSName,
    "Escape string": EscapeString,
    "Escape Unicode Characters": EscapeUnicodeCharacters,
    "Expand alphabet range": ExpandAlphabetRange,
    "Extract Files": ExtractFiles,
    "Extract ID3": ExtractID3,
    "Fang URL": FangURL,
    "Fernet Decrypt": FernetDecrypt,
    "Fernet Encrypt": FernetEncrypt,
    "File Tree": FileTree,
    "Fork": Fork,
    "Format MAC addresses": FormatMACAddresses,
    "Frequency distribution": FrequencyDistribution,
    "From BCD": FromBCD,
    "From Base": FromBase,
    "From Base32": FromBase32,
    "From Base45": FromBase45,
    "From Base58": FromBase58,
    "From Base62": FromBase62,
    "From Base64": FromBase64,
    "From Base85": FromBase85,
    "From Base92": FromBase92,
    "From Binary": FromBinary,
    "From Braille": FromBraille,
    "From Case Insensitive Regex": FromCaseInsensitiveRegex,
    "From Charcode": FromCharcode,
    "From Decimal": FromDecimal,
    "From Float": FromFloat,
    "From Hex": FromHex,
    "From Hex Content": FromHexContent,
    "From Hexdump": FromHexdump,
    "From Modhex": FromModhex,
    "From Morse Code": FromMorseCode,
    "From Octal": FromOctal,
    "From Quoted Printable": FromQuotedPrintable,
    "From UNIX Timestamp": FromUNIXTimestamp,
    "Fuzzy Match": FuzzyMatch,
    "Generate De Bruijn Sequence": GenerateDeBruijnSequence,
    "Generate HOTP": GenerateHOTP,
    "Generate Lorem Ipsum": GenerateLoremIpsum,
    "Generate TOTP": GenerateTOTP,
    "Get All Casings": GetAllCasings,
    "Get Time": GetTime,
    "Group IP addresses": GroupIPAddresses,
    "HTML To Text": HTMLToText,
    "HTTP request": HTTPRequest,
    "Hamming Distance": HammingDistance,
    "Haversine distance": HaversineDistance,
    "Head": Head,
    "IPv6 Transition Addresses": IPv6TransitionAddresses,
    "Index of Coincidence": IndexOfCoincidence,
    "JSON to CSV": JSONToCSV,
    "JSON to YAML": JSONtoYAML,
    "Jump": Jump,
    "Label": Label,
    "Levenshtein Distance": LevenshteinDistance,
    "Luhn Checksum": LuhnChecksum,
    "MIME Decoding": MIMEDecoding,
    "Magic": Magic,
    "Mean": Mean,
    "Median": Median,
    "Merge": Merge,
    "Microsoft Script Decoder": MicrosoftScriptDecoder,
    "Multiply": Multiply,
    "NOT": NOT,
    "Numberwang": Numberwang,
    "OR": OR,
    "Offset checker": OffsetChecker,
    "PEM to Hex": PEMToHex,
    "PHP Deserialize": PHPDeserialize,
    "PHP Serialize": PHPSerialize,
    "P-list Viewer": PLISTViewer,
    "Pad lines": PadLines,
    "Parse colour code": ParseColourCode,
    "Parse DateTime": ParseDateTime,
    "Parse IP range": ParseIPRange,
    "Parse IPv4 header": ParseIPv4Header,
    "Parse IPv6 address": ParseIPv6Address,
    "Parse SSH Host Key": ParseSSHHostKey,
    "Parse TCP": ParseTCP,
    "Parse TLS record": ParseTLSRecord,
    "Parse TLV": ParseTLV,
    "Parse UDP": ParseUDP,
    "Parse UNIX file permissions": ParseUNIXFilePermissions,
    "Play Media": PlayMedia,
    "Power Set": PowerSet,
    "RAKE": RAKE,
    "ROT13": ROT13,
    "ROT13 Brute Force": ROT13BruteForce,
    "ROT47": ROT47,
    "ROT47 Brute Force": ROT47BruteForce,
    "ROT8000": ROT8000,
    "Remove Diacritics": RemoveDiacritics,
    "Remove line numbers": RemoveLineNumbers,
    "Remove null bytes": RemoveNullBytes,
    "Remove whitespace": RemoveWhitespace,
    "Return": Return,
    "Reverse": Reverse,
    "Rotate left": RotateLeft,
    "Rotate right": RotateRight,
    "SUB": SUB,
    "Scan for Embedded Files": ScanForEmbeddedFiles,
    "Set Difference": SetDifference,
    "Set Intersection": SetIntersection,
    "Set Union": SetUnion,
    "Show Base64 offsets": ShowBase64Offsets,
    "Shuffle": Shuffle,
    "Sleep": Sleep,
    "Sort": Sort,
    "Split": Split,
    "Standard Deviation": StandardDeviation,
    "Strip HTML tags": StripHTMLTags,
    "Strip HTTP headers": StripHTTPHeaders,
    "Strip IPv4 header": StripIPv4Header,
    "Strip TCP header": StripTCPHeader,
    "Strip UDP header": StripUDPHeader,
    "Subsection": Subsection,
    "Substitute": Substitute,
    "Subtract": Subtract,
    "Sum": Sum,
    "Swap case": SwapCase,
    "Swap endianness": SwapEndianness,
    "Symmetric Difference": SymmetricDifference,
    "Tail": Tail,
    "Take bytes": TakeBytes,
    "Take nth bytes": TakeNthBytes,
    "To BCD": ToBCD,
    "To Base": ToBase,
    "To Base32": ToBase32,
    "To Base45": ToBase45,
    "To Base58": ToBase58,
    "To Base62": ToBase62,
    "To Base64": ToBase64,
    "To Base85": ToBase85,
    "To Base92": ToBase92,
    "To Binary": ToBinary,
    "To Braille": ToBraille,
    "To Case Insensitive Regex": ToCaseInsensitiveRegex,
    "To Charcode": ToCharcode,
    "To Decimal": ToDecimal,
    "To Float": ToFloat,
    "To Hex": ToHex,
    "To Hex Content": ToHexContent,
    "To Hexdump": ToHexdump,
    "To Lower case": ToLowerCase,
    "To Modhex": ToModhex,
    "To Morse Code": ToMorseCode,
    "To Octal": ToOctal,
    "To Quoted Printable": ToQuotedPrintable,
    "To Table": ToTable,
    "To UNIX Timestamp": ToUNIXTimestamp,
    "To Upper case": ToUpperCase,
    "Translate DateTime Format": TranslateDateTimeFormat,
    "UNIX Timestamp to Windows Filetime": UNIXTimestampToWindowsFiletime,
    "Unescape string": UnescapeString,
    "Unescape Unicode Characters": UnescapeUnicodeCharacters,
    "Unicode Text Format": UnicodeTextFormat,
    "Unique": Unique,
    "VarInt Decode": VarIntDecode,
    "VarInt Encode": VarIntEncode,
    "Windows Filetime to UNIX Timestamp": WindowsFiletimeToUNIXTimestamp,
    "XKCD Random Number": XKCDRandomNumber,
    "XOR": XOR,
    "XOR Brute Force": XORBruteForce,
    "YAML to JSON": YAMLToJSON,
};

export default OpModules;
