/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import AMFDecode from "../../operations/AMFDecode.js";
import AMFEncode from "../../operations/AMFEncode.js";
import CitrixCTX1Decode from "../../operations/CitrixCTX1Decode.js";
import CitrixCTX1Encode from "../../operations/CitrixCTX1Encode.js";
import DecodeText from "../../operations/DecodeText.js";
import EncodeText from "../../operations/EncodeText.js";
import FromHTMLEntity from "../../operations/FromHTMLEntity.js";
import FromPunycode from "../../operations/FromPunycode.js";
import NormaliseUnicode from "../../operations/NormaliseUnicode.js";
import RisonDecode from "../../operations/RisonDecode.js";
import RisonEncode from "../../operations/RisonEncode.js";
import TextEncodingBruteForce from "../../operations/TextEncodingBruteForce.js";
import ToHTMLEntity from "../../operations/ToHTMLEntity.js";
import ToPunycode from "../../operations/ToPunycode.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Encodings = {
    "AMF Decode": AMFDecode,
    "AMF Encode": AMFEncode,
    "Citrix CTX1 Decode": CitrixCTX1Decode,
    "Citrix CTX1 Encode": CitrixCTX1Encode,
    "Decode text": DecodeText,
    "Encode text": EncodeText,
    "From HTML Entity": FromHTMLEntity,
    "From Punycode": FromPunycode,
    "Normalise Unicode": NormaliseUnicode,
    "Rison Decode": RisonDecode,
    "Rison Encode": RisonEncode,
    "Text Encoding Brute Force": TextEncodingBruteForce,
    "To HTML Entity": ToHTMLEntity,
    "To Punycode": ToPunycode,
};

export default OpModules;
