/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import BLAKE2b from "../../operations/BLAKE2b.js";
import BLAKE2s from "../../operations/BLAKE2s.js";
import ConvertCoordinateFormat from "../../operations/ConvertCoordinateFormat.js";
import GOSTHash from "../../operations/GOSTHash.js";
import MurmurHash3 from "../../operations/MurmurHash3.js";
import ShowOnMap from "../../operations/ShowOnMap.js";
import Streebog from "../../operations/Streebog.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Hashing = {
    "BLAKE2b": BLAKE2b,
    "BLAKE2s": BLAKE2s,
    "Convert co-ordinate format": ConvertCoordinateFormat,
    "GOST Hash": GOSTHash,
    "MurmurHash3": MurmurHash3,
    "Show on map": ShowOnMap,
    "Streebog": Streebog,
};

export default OpModules;
