/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import AddTextToImage from "../../operations/AddTextToImage.js";
import BlurImage from "../../operations/BlurImage.js";
import ContainImage from "../../operations/ContainImage.js";
import ConvertImageFormat from "../../operations/ConvertImageFormat.js";
import CoverImage from "../../operations/CoverImage.js";
import CropImage from "../../operations/CropImage.js";
import DitherImage from "../../operations/DitherImage.js";
import ExtractEXIF from "../../operations/ExtractEXIF.js";
import ExtractLSB from "../../operations/ExtractLSB.js";
import ExtractRGBA from "../../operations/ExtractRGBA.js";
import FlipImage from "../../operations/FlipImage.js";
import GenerateImage from "../../operations/GenerateImage.js";
import GenerateQRCode from "../../operations/GenerateQRCode.js";
import ImageBrightnessContrast from "../../operations/ImageBrightnessContrast.js";
import ImageFilter from "../../operations/ImageFilter.js";
import ImageHueSaturationLightness from "../../operations/ImageHueSaturationLightness.js";
import ImageOpacity from "../../operations/ImageOpacity.js";
import InvertImage from "../../operations/InvertImage.js";
import NormaliseImage from "../../operations/NormaliseImage.js";
import ParseQRCode from "../../operations/ParseQRCode.js";
import RandomizeColourPalette from "../../operations/RandomizeColourPalette.js";
import RemoveEXIF from "../../operations/RemoveEXIF.js";
import RenderImage from "../../operations/RenderImage.js";
import ResizeImage from "../../operations/ResizeImage.js";
import RotateImage from "../../operations/RotateImage.js";
import SharpenImage from "../../operations/SharpenImage.js";
import SplitColourChannels from "../../operations/SplitColourChannels.js";
import ViewBitPlane from "../../operations/ViewBitPlane.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Image = {
    "Add Text To Image": AddTextToImage,
    "Blur Image": BlurImage,
    "Contain Image": ContainImage,
    "Convert Image Format": ConvertImageFormat,
    "Cover Image": CoverImage,
    "Crop Image": CropImage,
    "Dither Image": DitherImage,
    "Extract EXIF": ExtractEXIF,
    "Extract LSB": ExtractLSB,
    "Extract RGBA": ExtractRGBA,
    "Flip Image": FlipImage,
    "Generate Image": GenerateImage,
    "Generate QR Code": GenerateQRCode,
    "Image Brightness / Contrast": ImageBrightnessContrast,
    "Image Filter": ImageFilter,
    "Image Hue/Saturation/Lightness": ImageHueSaturationLightness,
    "Image Opacity": ImageOpacity,
    "Invert Image": InvertImage,
    "Normalise Image": NormaliseImage,
    "Parse QR Code": ParseQRCode,
    "Randomize Colour Palette": RandomizeColourPalette,
    "Remove EXIF": RemoveEXIF,
    "Render Image": RenderImage,
    "Resize Image": ResizeImage,
    "Rotate Image": RotateImage,
    "Sharpen Image": SharpenImage,
    "Split Colour Channels": SplitColourChannels,
    "View Bit Plane": ViewBitPlane,
};

export default OpModules;
