/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* Imports all modules for builds which do not load modules separately.
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import CiphersModule from "./Ciphers.js";
import DefaultModule from "./Default.js";
import EncodingsModule from "./Encodings.js";
import ImageModule from "./Image.js";
import CryptoModule from "./Crypto.js";
import SerialiseModule from "./Serialise.js";
import HashingModule from "./Hashing.js";
import BletchleyModule from "./Bletchley.js";
import CompressionModule from "./Compression.js";
import CodeModule from "./Code.js";
import DiffModule from "./Diiff.js";
import ShellcodeModule from "./Shellcode.js";
import ChartsModule from "./Charts.js";
import RegexModule from "./Regex.js";
import PGPModule from "./PGP.js";
import PublicKeyModule from "./PublicKey.js";
import JqModule from "./Jq.js";
import OCRModule from "./OCR.js";
import URLModule from "./URL.js";
import UserAgentModule from "./UserAgent.js";
import ProtobufModule from "./Protobuf.js";
import YaraModule from "./Yara.js";

const OpModules = {};

Object.assign(
    OpModules,
    CiphersModule,
    DefaultModule,
    EncodingsModule,
    ImageModule,
    CryptoModule,
    SerialiseModule,
    HashingModule,
    BletchleyModule,
    CompressionModule,
    CodeModule,
    DiffModule,
    ShellcodeModule,
    ChartsModule,
    RegexModule,
    PGPModule,
    PublicKeyModule,
    JqModule,
    OCRModule,
    URLModule,
    UserAgentModule,
    ProtobufModule,
    YaraModule,
);

export default OpModules;
