/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import GeneratePGPKeyPair from "../../operations/GeneratePGPKeyPair.js";
import PGPDecrypt from "../../operations/PGPDecrypt.js";
import PGPDecryptAndVerify from "../../operations/PGPDecryptAndVerify.js";
import PGPEncrypt from "../../operations/PGPEncrypt.js";
import PGPEncryptAndSign from "../../operations/PGPEncryptAndSign.js";
import PGPVerify from "../../operations/PGPVerify.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PGP = {
    "Generate PGP Key Pair": GeneratePGPKeyPair,
    "PGP Decrypt": PGPDecrypt,
    "PGP Decrypt and Verify": PGPDecryptAndVerify,
    "PGP Encrypt": PGPEncrypt,
    "PGP Encrypt and Sign": PGPEncryptAndSign,
    "PGP Verify": PGPVerify,
};

export default OpModules;
