/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import HexToObjectIdentifier from "../../operations/HexToObjectIdentifier.js";
import HexToPEM from "../../operations/HexToPEM.js";
import JWKToPem from "../../operations/JWKToPem.js";
import ObjectIdentifierToHex from "../../operations/ObjectIdentifierToHex.js";
import PEMToJWK from "../../operations/PEMToJWK.js";
import ParseASN1HexString from "../../operations/ParseASN1HexString.js";
import ParseCSR from "../../operations/ParseCSR.js";
import ParseX509CRL from "../../operations/ParseX509CRL.js";
import ParseX509Certificate from "../../operations/ParseX509Certificate.js";
import PubKeyFromCert from "../../operations/PubKeyFromCert.js";
import PubKeyFromPrivKey from "../../operations/PubKeyFromPrivKey.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.PublicKey = {
    "Hex to Object Identifier": HexToObjectIdentifier,
    "Hex to PEM": HexToPEM,
    "JWK to PEM": JWKToPem,
    "Object Identifier to Hex": ObjectIdentifierToHex,
    "PEM to JWK": PEMToJWK,
    "Parse ASN.1 hex string": ParseASN1HexString,
    "Parse CSR": ParseCSR,
    "Parse X.509 CRL": ParseX509CRL,
    "Parse X.509 certificate": ParseX509Certificate,
    "Public Key from Certificate": PubKeyFromCert,
    "Public Key from Private Key": PubKeyFromPrivKey,
};

export default OpModules;
