/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import ExtractDates from "../../operations/ExtractDates.js";
import ExtractDomains from "../../operations/ExtractDomains.js";
import ExtractEmailAddresses from "../../operations/ExtractEmailAddresses.js";
import ExtractFilePaths from "../../operations/ExtractFilePaths.js";
import ExtractHashes from "../../operations/ExtractHashes.js";
import ExtractIPAddresses from "../../operations/ExtractIPAddresses.js";
import ExtractMACAddresses from "../../operations/ExtractMACAddresses.js";
import ExtractURLs from "../../operations/ExtractURLs.js";
import Filter from "../../operations/Filter.js";
import FindReplace from "../../operations/FindReplace.js";
import Register from "../../operations/Register.js";
import RegularExpression from "../../operations/RegularExpression.js";
import Strings from "../../operations/Strings.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Regex = {
    "Extract dates": ExtractDates,
    "Extract domains": ExtractDomains,
    "Extract email addresses": ExtractEmailAddresses,
    "Extract file paths": ExtractFilePaths,
    "Extract hashes": ExtractHashes,
    "Extract IP addresses": ExtractIPAddresses,
    "Extract MAC addresses": ExtractMACAddresses,
    "Extract URLs": ExtractURLs,
    "Filter": Filter,
    "Find / Replace": FindReplace,
    "Register": Register,
    "Regular expression": RegularExpression,
    "Strings": Strings,
};

export default OpModules;
