/**
* THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateConfig.js
*
* @author n1474335 [n1474335@gmail.com]
* @copyright Crown Copyright 2025
* @license Apache-2.0
*/
import AvroToJSON from "../../operations/AvroToJSON.js";
import BSONDeserialise from "../../operations/BSONDeserialise.js";
import BSONSerialise from "../../operations/BSONSerialise.js";
import CBORDecode from "../../operations/CBORDecode.js";
import CBOREncode from "../../operations/CBOREncode.js";
import ParseObjectIDTimestamp from "../../operations/ParseObjectIDTimestamp.js";

const OpModules = typeof self === "undefined" ? {} : self.OpModules || {};

OpModules.Serialise = {
    "Avro to JSON": AvroToJSON,
    "BSON deserialise": BSONDeserialise,
    "BSON serialise": BSONSerialise,
    "CBOR Decode": CBORDecode,
    "CBOR Encode": CBOREncode,
    "Parse ObjectID timestamp": ParseObjectIDTimestamp,
};

export default OpModules;
