/**
 * THIS FILE IS AUTOMATICALLY GENERATED BY src/core/config/scripts/generateOpsIndex.js
 *
 * @author n1474335 [n1474335@gmail.com]
 * @copyright Crown Copyright 2025
 * @license Apache-2.0
 */
import A1Z26CipherDecode from "./operations/A1Z26CipherDecode.js";
import A1Z26CipherEncode from "./operations/A1Z26CipherEncode.js";
import ADD from "./operations/ADD.js";
import AddLineNumbers from "./operations/AddLineNumbers.js";
import AddTextToImage from "./operations/AddTextToImage.js";
import Adler32Checksum from "./operations/Adler32Checksum.js";
import AESDecrypt from "./operations/AESDecrypt.js";
import AESEncrypt from "./operations/AESEncrypt.js";
import AESKeyUnwrap from "./operations/AESKeyUnwrap.js";
import AESKeyWrap from "./operations/AESKeyWrap.js";
import AffineCipherDecode from "./operations/AffineCipherDecode.js";
import AffineCipherEncode from "./operations/AffineCipherEncode.js";
import AMFDecode from "./operations/AMFDecode.js";
import AMFEncode from "./operations/AMFEncode.js";
import AnalyseHash from "./operations/AnalyseHash.js";
import AND from "./operations/AND.js";
import Argon2 from "./operations/Argon2.js";
import Argon2Compare from "./operations/Argon2Compare.js";
import AtbashCipher from "./operations/AtbashCipher.js";
import AvroToJSON from "./operations/AvroToJSON.js";
import BaconCipherDecode from "./operations/BaconCipherDecode.js";
import BaconCipherEncode from "./operations/BaconCipherEncode.js";
import Bcrypt from "./operations/Bcrypt.js";
import BcryptCompare from "./operations/BcryptCompare.js";
import BcryptParse from "./operations/BcryptParse.js";
import BifidCipherDecode from "./operations/BifidCipherDecode.js";
import BifidCipherEncode from "./operations/BifidCipherEncode.js";
import BitShiftLeft from "./operations/BitShiftLeft.js";
import BitShiftRight from "./operations/BitShiftRight.js";
import BLAKE2b from "./operations/BLAKE2b.js";
import BLAKE2s from "./operations/BLAKE2s.js";
import BlowfishDecrypt from "./operations/BlowfishDecrypt.js";
import BlowfishEncrypt from "./operations/BlowfishEncrypt.js";
import BlurImage from "./operations/BlurImage.js";
import Bombe from "./operations/Bombe.js";
import BSONDeserialise from "./operations/BSONDeserialise.js";
import BSONSerialise from "./operations/BSONSerialise.js";
import Bzip2Compress from "./operations/Bzip2Compress.js";
import Bzip2Decompress from "./operations/Bzip2Decompress.js";
import CaesarBoxCipher from "./operations/CaesarBoxCipher.js";
import CaretMdecode from "./operations/CaretMdecode.js";
import CartesianProduct from "./operations/CartesianProduct.js";
import CBORDecode from "./operations/CBORDecode.js";
import CBOREncode from "./operations/CBOREncode.js";
import CetaceanCipherDecode from "./operations/CetaceanCipherDecode.js";
import CetaceanCipherEncode from "./operations/CetaceanCipherEncode.js";
import ChaCha from "./operations/ChaCha.js";
import ChangeIPFormat from "./operations/ChangeIPFormat.js";
import ChiSquare from "./operations/ChiSquare.js";
import CipherSaber2Decrypt from "./operations/CipherSaber2Decrypt.js";
import CipherSaber2Encrypt from "./operations/CipherSaber2Encrypt.js";
import CitrixCTX1Decode from "./operations/CitrixCTX1Decode.js";
import CitrixCTX1Encode from "./operations/CitrixCTX1Encode.js";
import CMAC from "./operations/CMAC.js";
import Colossus from "./operations/Colossus.js";
import Comment from "./operations/Comment.js";
import CompareCTPHHashes from "./operations/CompareCTPHHashes.js";
import CompareSSDEEPHashes from "./operations/CompareSSDEEPHashes.js";
import ConditionalJump from "./operations/ConditionalJump.js";
import ContainImage from "./operations/ContainImage.js";
import ConvertArea from "./operations/ConvertArea.js";
import ConvertCoordinateFormat from "./operations/ConvertCoordinateFormat.js";
import ConvertDataUnits from "./operations/ConvertDataUnits.js";
import ConvertDistance from "./operations/ConvertDistance.js";
import ConvertImageFormat from "./operations/ConvertImageFormat.js";
import ConvertLeetSpeak from "./operations/ConvertLeetSpeak.js";
import ConvertMass from "./operations/ConvertMass.js";
import ConvertSpeed from "./operations/ConvertSpeed.js";
import ConvertToNATOAlphabet from "./operations/ConvertToNATOAlphabet.js";
import CountOccurrences from "./operations/CountOccurrences.js";
import CoverImage from "./operations/CoverImage.js";
import CRCChecksum from "./operations/CRCChecksum.js";
import CropImage from "./operations/CropImage.js";
import CSSBeautify from "./operations/CSSBeautify.js";
import CSSMinify from "./operations/CSSMinify.js";
import CSSSelector from "./operations/CSSSelector.js";
import CSVToJSON from "./operations/CSVToJSON.js";
import CTPH from "./operations/CTPHH.js";
import DateTimeDelta from "./operations/DateTimeDelta.js";
import DechunkHTTPResponse from "./operations/DechunkHTTPResponse.js";
import DecodeNetBIOSName from "./operations/DecodeNetBIOSName.js";
import DecodeText from "./operations/DecodeText.js";
import DefangIPAddresses from "./operations/DefangIPAddresses.js";
import DefangURL from "./operations/DefangURL.js";
import DeriveEVPKey from "./operations/DeriveEVPKey.js";
import DeriveHKDFKey from "./operations/DeriveHKDFKey.js";
import DerivePBKDF2Key from "./operations/DerivePBKDF2Key.js";
import DESDecrypt from "./operations/DESDecrypt.js";
import DESEncrypt from "./operations/DESEncrypt.js";
import DetectFileType from "./operations/DetectFileType.js";
import Diff from "./operations/Difff.js";
import DisassembleX86 from "./operations/DisassembleX86.js";
import DitherImage from "./operations/DitherImage.js";
import Divide from "./operations/Divide.js";
import DNSOverHTTPS from "./operations/DNSOverHTTPS.js";
import DropBytes from "./operations/DropBytes.js";
import DropNthBytes from "./operations/DropNthBytes.js";
import ECDSASign from "./operations/ECDSASign.js";
import ECDSASignatureConversion from "./operations/ECDSASignatureConversion.js";
import ECDSAVerify from "./operations/ECDSAVerify.js";
import ELFInfo from "./operations/ELFInfo.js";
import EncodeNetBIOSName from "./operations/EncodeNetBIOSName.js";
import EncodeText from "./operations/EncodeText.js";
import Enigma from "./operations/Enigma.js";
import Entropy from "./operations/Entropy.js";
import EscapeString from "./operations/EscapeString.js";
import EscapeUnicodeCharacters from "./operations/EscapeUnicodeCharacters.js";
import ExpandAlphabetRange from "./operations/ExpandAlphabetRange.js";
import ExtractDates from "./operations/ExtractDates.js";
import ExtractDomains from "./operations/ExtractDomains.js";
import ExtractEmailAddresses from "./operations/ExtractEmailAddresses.js";
import ExtractEXIF from "./operations/ExtractEXIF.js";
import ExtractFilePaths from "./operations/ExtractFilePaths.js";
import ExtractFiles from "./operations/ExtractFiles.js";
import ExtractHashes from "./operations/ExtractHashes.js";
import ExtractID3 from "./operations/ExtractID3.js";
import ExtractIPAddresses from "./operations/ExtractIPAddresses.js";
import ExtractLSB from "./operations/ExtractLSB.js";
import ExtractMACAddresses from "./operations/ExtractMACAddresses.js";
import ExtractRGBA from "./operations/ExtractRGBA.js";
import ExtractURLs from "./operations/ExtractURLs.js";
import FangURL from "./operations/FangURL.js";
import FernetDecrypt from "./operations/FernetDecrypt.js";
import FernetEncrypt from "./operations/FernetEncrypt.js";
import FileTree from "./operations/FileTree.js";
import Filter from "./operations/Filter.js";
import FindReplace from "./operations/FindReplace.js";
import Fletcher16Checksum from "./operations/Fletcher16Checksum.js";
import Fletcher32Checksum from "./operations/Fletcher32Checksum.js";
import Fletcher64Checksum from "./operations/Fletcher64Checksum.js";
import Fletcher8Checksum from "./operations/Fletcher8Checksum.js";
import FlipImage from "./operations/FlipImage.js";
import Fork from "./operations/Fork.js";
import FormatMACAddresses from "./operations/FormatMACAddresses.js";
import FrequencyDistribution from "./operations/FrequencyDistribution.js";
import FromBase from "./operations/FromBase.js";
import FromBase32 from "./operations/FromBase32.js";
import FromBase45 from "./operations/FromBase45.js";
import FromBase58 from "./operations/FromBase58.js";
import FromBase62 from "./operations/FromBase62.js";
import FromBase64 from "./operations/FromBase64.js";
import FromBase85 from "./operations/FromBase85.js";
import FromBase92 from "./operations/FromBase92.js";
import FromBCD from "./operations/FromBCD.js";
import FromBinary from "./operations/FromBinary.js";
import FromBraille from "./operations/FromBraille.js";
import FromCaseInsensitiveRegex from "./operations/FromCaseInsensitiveRegex.js";
import FromCharcode from "./operations/FromCharcode.js";
import FromDecimal from "./operations/FromDecimal.js";
import FromFloat from "./operations/FromFloat.js";
import FromHex from "./operations/FromHex.js";
import FromHexContent from "./operations/FromHexContent.js";
import FromHexdump from "./operations/FromHexdump.js";
import FromHTMLEntity from "./operations/FromHTMLEntity.js";
import FromMessagePack from "./operations/FromMessagePack.js";
import FromModhex from "./operations/FromModhex.js";
import FromMorseCode from "./operations/FromMorseCode.js";
import FromOctal from "./operations/FromOctal.js";
import FromPunycode from "./operations/FromPunycode.js";
import FromQuotedPrintable from "./operations/FromQuotedPrintable.js";
import FromUNIXTimestamp from "./operations/FromUNIXTimestamp.js";
import FuzzyMatch from "./operations/FuzzyMatch.js";
import GenerateAllHashes from "./operations/GenerateAllHashes.js";
import GenerateDeBruijnSequence from "./operations/GenerateDeBruijnSequence.js";
import GenerateECDSAKeyPair from "./operations/GenerateECDSAKeyPair.js";
import GenerateHOTP from "./operations/GenerateHOTP.js";
import GenerateImage from "./operations/GenerateImage.js";
import GenerateLoremIpsum from "./operations/GenerateLoremIpsum.js";
import GeneratePGPKeyPair from "./operations/GeneratePGPKeyPair.js";
import GenerateQRCode from "./operations/GenerateQRCode.js";
import GenerateRSAKeyPair from "./operations/GenerateRSAKeyPair.js";
import GenerateTOTP from "./operations/GenerateTOTP.js";
import GenerateUUID from "./operations/GenerateUUID.js";
import GenericCodeBeautify from "./operations/GenericCodeBeautify.js";
import GetAllCasings from "./operations/GetAllCasings.js";
import GetTime from "./operations/GetTime.js";
import GOSTDecrypt from "./operations/GOSTDecrypt.js";
import GOSTEncrypt from "./operations/GOSTEncrypt.js";
import GOSTHash from "./operations/GOSTHash.js";
import GOSTKeyUnwrap from "./operations/GOSTKeyUnwrap.js";
import GOSTKeyWrap from "./operations/GOSTKeyWrap.js";
import GOSTSign from "./operations/GOSTSign.js";
import GOSTVerify from "./operations/GOSTVerify.js";
import GroupIPAddresses from "./operations/GroupIPAddresses.js";
import Gunzip from "./operations/Gunzip.js";
import Gzip from "./operations/Gzip.js";
import HammingDistance from "./operations/HammingDistance.js";
import HAS160 from "./operations/HAS160.js";
import HASSHClientFingerprint from "./operations/HASSHClientFingerprint.js";
import HASSHServerFingerprint from "./operations/HASSHServerFingerprint.js";
import HaversineDistance from "./operations/HaversineDistance.js";
import Head from "./operations/Head.js";
import HeatmapChart from "./operations/HeatmapChart.js";
import HexDensityChart from "./operations/HexDensityChart.js";
import HexToObjectIdentifier from "./operations/HexToObjectIdentifier.js";
import HexToPEM from "./operations/HexToPEM.js";
import HMAC from "./operations/HMAC.js";
import HTMLToText from "./operations/HTMLToText.js";
import HTTPRequest from "./operations/HTTPRequest.js";
import ImageBrightnessContrast from "./operations/ImageBrightnessContrast.js";
import ImageFilter from "./operations/ImageFilter.js";
import ImageHueSaturationLightness from "./operations/ImageHueSaturationLightness.js";
import ImageOpacity from "./operations/ImageOpacity.js";
import IndexOfCoincidence from "./operations/IndexOfCoincidence.js";
import InvertImage from "./operations/InvertImage.js";
import IPv6TransitionAddresses from "./operations/IPv6TransitionAddresses.js";
import JA3Fingerprint from "./operations/JA3Fingerprint.js";
import JA3SFingerprint from "./operations/JA3SFingerprint.js";
import JA4Fingerprint from "./operations/JA4Fingerprint.js";
import JA4ServerFingerprint from "./operations/JA4ServerFingerprint.js";
import JavaScriptBeautify from "./operations/JavaScriptBeautify.js";
import JavaScriptMinify from "./operations/JavaScriptMinify.js";
import JavaScriptParser from "./operations/JavaScriptParser.js";
import JPathExpression from "./operations/JPathExpression.js";
import Jq from "./operations/Jq.js";
import JSONBeautify from "./operations/JSONBeautify.js";
import JSONMinify from "./operations/JSONMinify.js";
import JSONToCSV from "./operations/JSONToCSV.js";
import JSONtoYAML from "./operations/JSONtoYAML.js";
import Jump from "./operations/Jump.js";
import JWKToPem from "./operations/JWKToPem.js";
import JWTDecode from "./operations/JWTDecode.js";
import JWTSign from "./operations/JWTSign.js";
import JWTVerify from "./operations/JWTVerify.js";
import Keccak from "./operations/Keccak.js";
import Label from "./operations/Label.js";
import LevenshteinDistance from "./operations/LevenshteinDistance.js";
import LMHash from "./operations/LMHash.js";
import Lorenz from "./operations/Lorenz.js";
import LS47Decrypt from "./operations/LS47Decrypt.js";
import LS47Encrypt from "./operations/LS47Encrypt.js";
import LuhnChecksum from "./operations/LuhnChecksum.js";
import LZ4Compress from "./operations/LZ4Compress.js";
import LZ4Decompress from "./operations/LZ4Decompress.js";
import LZMACompress from "./operations/LZMACompress.js";
import LZMADecompress from "./operations/LZMADecompress.js";
import LZNT1Decompress from "./operations/LZNT1Decompress.js";
import LZStringCompress from "./operations/LZStringCompress.js";
import LZStringDecompress from "./operations/LZStringDecompress.js";
import Magic from "./operations/Magic.js";
import MD2 from "./operations/MD2.js";
import MD4 from "./operations/MD4.js";
import MD5 from "./operations/MD5.js";
import MD6 from "./operations/MD6.js";
import Mean from "./operations/Mean.js";
import Median from "./operations/Median.js";
import Merge from "./operations/Merge.js";
import MicrosoftScriptDecoder from "./operations/MicrosoftScriptDecoder.js";
import MIMEDecoding from "./operations/MIMEDecoding.js";
import MultipleBombe from "./operations/MultipleBombe.js";
import Multiply from "./operations/Multiply.js";
import MurmurHash3 from "./operations/MurmurHash3.js";
import NormaliseImage from "./operations/NormaliseImage.js";
import NormaliseUnicode from "./operations/NormaliseUnicode.js";
import NOT from "./operations/NOT.js";
import NTHash from "./operations/NTHash.js";
import Numberwang from "./operations/Numberwang.js";
import ObjectIdentifierToHex from "./operations/ObjectIdentifierToHex.js";
import OffsetChecker from "./operations/OffsetChecker.js";
import OpticalCharacterRecognition from "./operations/OpticalCharacterRecognition.js";
import OR from "./operations/OR.js";
import PadLines from "./operations/PadLines.js";
import ParseASN1HexString from "./operations/ParseASN1HexString.js";
import ParseColourCode from "./operations/ParseColourCode.js";
import ParseCSR from "./operations/ParseCSR.js";
import ParseDateTime from "./operations/ParseDateTime.js";
import ParseIPRange from "./operations/ParseIPRange.js";
import ParseIPv4Header from "./operations/ParseIPv4Header.js";
import ParseIPv6Address from "./operations/ParseIPv6Address.js";
import ParseObjectIDTimestamp from "./operations/ParseObjectIDTimestamp.js";
import ParseQRCode from "./operations/ParseQRCode.js";
import ParseSSHHostKey from "./operations/ParseSSHHostKey.js";
import ParseTCP from "./operations/ParseTCP.js";
import ParseTLSRecord from "./operations/ParseTLSRecord.js";
import ParseTLV from "./operations/ParseTLV.js";
import ParseUDP from "./operations/ParseUDP.js";
import ParseUNIXFilePermissions from "./operations/ParseUNIXFilePermissions.js";
import ParseURI from "./operations/ParseURI.js";
import ParseUserAgent from "./operations/ParseUserAgent.js";
import ParseX509Certificate from "./operations/ParseX509Certificate.js";
import ParseX509CRL from "./operations/ParseX509CRL.js";
import PEMToHex from "./operations/PEMToHex.js";
import PEMToJWK from "./operations/PEMToJWK.js";
import PGPDecrypt from "./operations/PGPDecrypt.js";
import PGPDecryptAndVerify from "./operations/PGPDecryptAndVerify.js";
import PGPEncrypt from "./operations/PGPEncrypt.js";
import PGPEncryptAndSign from "./operations/PGPEncryptAndSign.js";
import PGPVerify from "./operations/PGPVerify.js";
import PHPDeserialize from "./operations/PHPDeserialize.js";
import PHPSerialize from "./operations/PHPSerialize.js";
import PlayMedia from "./operations/PlayMedia.js";
import PLISTViewer from "./operations/PLISTViewer.js";
import PowerSet from "./operations/PowerSet.js";
import ProtobufDecode from "./operations/ProtobufDecode.js";
import ProtobufEncode from "./operations/ProtobufEncode.js";
import PseudoRandomNumberGenerator from "./operations/PseudoRandomNumberGenerator.js";
import PubKeyFromCert from "./operations/PubKeyFromCert.js";
import PubKeyFromPrivKey from "./operations/PubKeyFromPrivKey.js";
import Rabbit from "./operations/Rabbit.js";
import RailFenceCipherDecode from "./operations/RailFenceCipherDecode.js";
import RailFenceCipherEncode from "./operations/RailFenceCipherEncode.js";
import RAKE from "./operations/RAKE.js";
import RandomizeColourPalette from "./operations/RandomizeColourPalette.js";
import RawDeflate from "./operations/RawDeflate.js";
import RawInflate from "./operations/RawInflate.js";
import RC2Decrypt from "./operations/RC2Decrypt.js";
import RC2Encrypt from "./operations/RC2Encrypt.js";
import RC4 from "./operations/RC4.js";
import RC4Drop from "./operations/RC4Drop.js";
import Register from "./operations/Register.js";
import RegularExpression from "./operations/RegularExpression.js";
import RemoveDiacritics from "./operations/RemoveDiacritics.js";
import RemoveEXIF from "./operations/RemoveEXIF.js";
import RemoveLineNumbers from "./operations/RemoveLineNumbers.js";
import RemoveNullBytes from "./operations/RemoveNullBytes.js";
import RemoveWhitespace from "./operations/RemoveWhitespace.js";
import RenderImage from "./operations/RenderImage.js";
import RenderMarkdown from "./operations/RenderMarkdown.js";
import ResizeImage from "./operations/ResizeImage.js";
import Return from "./operations/Return.js";
import Reverse from "./operations/Reverse.js";
import RIPEMD from "./operations/RIPEMD.js";
import RisonDecode from "./operations/RisonDecode.js";
import RisonEncode from "./operations/RisonEncode.js";
import ROT13 from "./operations/ROT13.js";
import ROT13BruteForce from "./operations/ROT13BruteForce.js";
import ROT47 from "./operations/ROT47.js";
import ROT47BruteForce from "./operations/ROT47BruteForce.js";
import ROT8000 from "./operations/ROT8000.js";
import RotateImage from "./operations/RotateImage.js";
import RotateLeft from "./operations/RotateLeft.js";
import RotateRight from "./operations/RotateRight.js";
import RSADecrypt from "./operations/RSADecrypt.js";
import RSAEncrypt from "./operations/RSAEncrypt.js";
import RSASign from "./operations/RSASign.js";
import RSAVerify from "./operations/RSAVerify.js";
import Salsa20 from "./operations/Salsa20.js";
import ScanForEmbeddedFiles from "./operations/ScanForEmbeddedFiles.js";
import ScatterChart from "./operations/ScatterChart.js";
import Scrypt from "./operations/Scrypt.js";
import SeriesChart from "./operations/SeriesChart.js";
import SetDifference from "./operations/SetDifference.js";
import SetIntersection from "./operations/SetIntersection.js";
import SetUnion from "./operations/SetUnion.js";
import SHA0 from "./operations/SHA0.js";
import SHA1 from "./operations/SHA1.js";
import SHA2 from "./operations/SHA2.js";
import SHA3 from "./operations/SHA3.js";
import Shake from "./operations/Shake.js";
import SharpenImage from "./operations/SharpenImage.js";
import ShowBase64Offsets from "./operations/ShowBase64Offsets.js";
import ShowOnMap from "./operations/ShowOnMap.js";
import Shuffle from "./operations/Shuffle.js";
import SIGABA from "./operations/SIGABA.js";
import Sleep from "./operations/Sleep.js";
import SM2Decrypt from "./operations/SM2Decrypt.js";
import SM2Encrypt from "./operations/SM2Encrypt.js";
import SM3 from "./operations/SM3.js";
import SM4Decrypt from "./operations/SM4Decrypt.js";
import SM4Encrypt from "./operations/SM4Encrypt.js";
import Snefru from "./operations/Snefru.js";
import Sort from "./operations/Sort.js";
import Split from "./operations/Split.js";
import SplitColourChannels from "./operations/SplitColourChannels.js";
import SQLBeautify from "./operations/SQLBeautify.js";
import SQLMinify from "./operations/SQLMinify.js";
import SSDEEP from "./operations/SSDEEEP.js";
import StandardDeviation from "./operations/StandardDeviation.js";
import Streebog from "./operations/Streebog.js";
import Strings from "./operations/Strings.js";
import StripHTMLTags from "./operations/StripHTMLTags.js";
import StripHTTPHeaders from "./operations/StripHTTPHeaders.js";
import StripIPv4Header from "./operations/StripIPv4Header.js";
import StripTCPHeader from "./operations/StripTCPHeader.js";
import StripUDPHeader from "./operations/StripUDPHeader.js";
import SUB from "./operations/SUB.js";
import Subsection from "./operations/Subsection.js";
import Substitute from "./operations/Substitute.js";
import Subtract from "./operations/Subtract.js";
import Sum from "./operations/Sum.js";
import SwapCase from "./operations/SwapCase.js";
import SwapEndianness from "./operations/SwapEndianness.js";
import SymmetricDifference from "./operations/SymmetricDifference.js";
import SyntaxHighlighter from "./operations/SyntaxHighlighter.js";
import Tail from "./operations/Tail.js";
import TakeBytes from "./operations/TakeBytes.js";
import TakeNthBytes from "./operations/TakeNthBytes.js";
import Tar from "./operations/Tar.js";
import TCPIPChecksum from "./operations/TCPIPChecksum.js";
import TextEncodingBruteForce from "./operations/TextEncodingBruteForce.js";
import ToBase from "./operations/ToBase.js";
import ToBase32 from "./operations/ToBase32.js";
import ToBase45 from "./operations/ToBase45.js";
import ToBase58 from "./operations/ToBase58.js";
import ToBase62 from "./operations/ToBase62.js";
import ToBase64 from "./operations/ToBase64.js";
import ToBase85 from "./operations/ToBase85.js";
import ToBase92 from "./operations/ToBase92.js";
import ToBCD from "./operations/ToBCD.js";
import ToBinary from "./operations/ToBinary.js";
import ToBraille from "./operations/ToBraille.js";
import ToCamelCase from "./operations/ToCamelCase.js";
import ToCaseInsensitiveRegex from "./operations/ToCaseInsensitiveRegex.js";
import ToCharcode from "./operations/ToCharcode.js";
import ToDecimal from "./operations/ToDecimal.js";
import ToFloat from "./operations/ToFloat.js";
import ToHex from "./operations/ToHex.js";
import ToHexContent from "./operations/ToHexContent.js";
import ToHexdump from "./operations/ToHexdump.js";
import ToHTMLEntity from "./operations/ToHTMLEntity.js";
import ToKebabCase from "./operations/ToKebabCase.js";
import ToLowerCase from "./operations/ToLowerCase.js";
import ToMessagePack from "./operations/ToMessagePack.js";
import ToModhex from "./operations/ToModhex.js";
import ToMorseCode from "./operations/ToMorseCode.js";
import ToOctal from "./operations/ToOctal.js";
import ToPunycode from "./operations/ToPunycode.js";
import ToQuotedPrintable from "./operations/ToQuotedPrintable.js";
import ToSnakeCase from "./operations/ToSnakeCase.js";
import ToTable from "./operations/ToTable.js";
import ToUNIXTimestamp from "./operations/ToUNIXTimestamp.js";
import ToUpperCase from "./operations/ToUpperCase.js";
import TranslateDateTimeFormat from "./operations/TranslateDateTimeFormat.js";
import TripleDESDecrypt from "./operations/TripleDESDecrypt.js";
import TripleDESEncrypt from "./operations/TripleDESEncrypt.js";
import Typex from "./operations/Typex.js";
import UnescapeString from "./operations/UnescapeString.js";
import UnescapeUnicodeCharacters from "./operations/UnescapeUnicodeCharacters.js";
import UnicodeTextFormat from "./operations/UnicodeTextFormat.js";
import Unique from "./operations/Unique.js";
import UNIXTimestampToWindowsFiletime from "./operations/UNIXTimestampToWindowsFiletime.js";
import Untar from "./operations/Untar.js";
import Unzip from "./operations/Unzip.js";
import URLDecode from "./operations/URLDecode.js";
import URLEncode from "./operations/URLEncode.js";
import VarIntDecode from "./operations/VarIntDecode.js";
import VarIntEncode from "./operations/VarIntEncode.js";
import ViewBitPlane from "./operations/ViewBitPlane.js";
import VigenèreDecode from "./operations/VigenèreDecode.js";
import VigenèreEncode from "./operations/VigenèreEncode.js";
import Whirlpool from "./operations/Whirlpool.js";
import WindowsFiletimeToUNIXTimestamp from "./operations/WindowsFiletimeToUNIXTimestamp.js";
import XKCDRandomNumber from "./operations/XKCDRandomNumber.js";
import XMLBeautify from "./operations/XMLBeautify.js";
import XMLMinify from "./operations/XMLMinify.js";
import XOR from "./operations/XOR.js";
import XORBruteForce from "./operations/XORBruteForce.js";
import XPathExpression from "./operations/XPathExpression.js";
import XSalsa20 from "./operations/XSalsa20.js";
import XXTEADecrypt from "./operations/XXTEADecrypt.js";
import XXTEAEncrypt from "./operations/XXTEAEncrypt.js";
import YAMLToJSON from "./operations/YAMLToJSON.js";
import YARARules from "./operations/YARARules.js";
import Zip from "./operations/Zip.js";
import ZlibDeflate from "./operations/ZlibDeflate.js";
import ZlibInflate from "./operations/ZlibInflate.js";
import { Buffer } from "buffer";

const app = {
  A1Z26CipherDecode,
  A1Z26CipherEncode,
  ADD,
  AddLineNumbers,
  AddTextToImage,
  Adler32Checksum,
  AESDecrypt,
  AESEncrypt,
  AESKeyUnwrap,
  AESKeyWrap,
  AffineCipherDecode,
  AffineCipherEncode,
  AMFDecode,
  AMFEncode,
  AnalyseHash,
  AND,
  Argon2,
  Argon2Compare,
  AtbashCipher,
  AvroToJSON,
  BaconCipherDecode,
  BaconCipherEncode,
  Bcrypt,
  BcryptCompare,
  BcryptParse,
  BifidCipherDecode,
  BifidCipherEncode,
  BitShiftLeft,
  BitShiftRight,
  BLAKE2b,
  BLAKE2s,
  BlowfishDecrypt,
  BlowfishEncrypt,
  BlurImage,
  Bombe,
  BSONDeserialise,
  BSONSerialise,
  Bzip2Compress,
  Bzip2Decompress,
  CaesarBoxCipher,
  CaretMdecode,
  CartesianProduct,
  CBORDecode,
  CBOREncode,
  CetaceanCipherDecode,
  CetaceanCipherEncode,
  ChaCha,
  ChangeIPFormat,
  ChiSquare,
  CipherSaber2Decrypt,
  CipherSaber2Encrypt,
  CitrixCTX1Decode,
  CitrixCTX1Encode,
  CMAC,
  Colossus,
  Comment,
  CompareCTPHHashes,
  CompareSSDEEPHashes,
  ConditionalJump,
  ContainImage,
  ConvertArea,
  ConvertCoordinateFormat,
  ConvertDataUnits,
  ConvertDistance,
  ConvertImageFormat,
  ConvertLeetSpeak,
  ConvertMass,
  ConvertSpeed,
  ConvertToNATOAlphabet,
  CountOccurrences,
  CoverImage,
  CRCChecksum,
  CropImage,
  CSSBeautify,
  CSSMinify,
  CSSSelector,
  CSVToJSON,
  CTPH,
  DateTimeDelta,
  DechunkHTTPResponse,
  DecodeNetBIOSName,
  DecodeText,
  DefangIPAddresses,
  DefangURL,
  DeriveEVPKey,
  DeriveHKDFKey,
  DerivePBKDF2Key,
  DESDecrypt,
  DESEncrypt,
  DetectFileType,
  Diff,
  DisassembleX86,
  DitherImage,
  Divide,
  DNSOverHTTPS,
  DropBytes,
  DropNthBytes,
  ECDSASign,
  ECDSASignatureConversion,
  ECDSAVerify,
  ELFInfo,
  EncodeNetBIOSName,
  EncodeText,
  Enigma,
  Entropy,
  EscapeString,
  EscapeUnicodeCharacters,
  ExpandAlphabetRange,
  ExtractDates,
  ExtractDomains,
  ExtractEmailAddresses,
  ExtractEXIF,
  ExtractFilePaths,
  ExtractFiles,
  ExtractHashes,
  ExtractID3,
  ExtractIPAddresses,
  ExtractLSB,
  ExtractMACAddresses,
  ExtractRGBA,
  ExtractURLs,
  FangURL,
  FernetDecrypt,
  FernetEncrypt,
  FileTree,
  Filter,
  FindReplace,
  Fletcher16Checksum,
  Fletcher32Checksum,
  Fletcher64Checksum,
  Fletcher8Checksum,
  FlipImage,
  Fork,
  FormatMACAddresses,
  FrequencyDistribution,
  FromBase,
  FromBase32,
  FromBase45,
  FromBase58,
  FromBase62,
  FromBase64,
  FromBase85,
  FromBase92,
  FromBCD,
  FromBinary,
  FromBraille,
  FromCaseInsensitiveRegex,
  FromCharcode,
  FromDecimal,
  FromFloat,
  FromHex,
  FromHexContent,
  FromHexdump,
  FromHTMLEntity,
  FromMessagePack,
  FromModhex,
  FromMorseCode,
  FromOctal,
  FromPunycode,
  FromQuotedPrintable,
  FromUNIXTimestamp,
  FuzzyMatch,
  GenerateAllHashes,
  GenerateDeBruijnSequence,
  GenerateECDSAKeyPair,
  GenerateHOTP,
  GenerateImage,
  GenerateLoremIpsum,
  GeneratePGPKeyPair,
  GenerateQRCode,
  GenerateRSAKeyPair,
  GenerateTOTP,
  GenerateUUID,
  GenericCodeBeautify,
  GetAllCasings,
  GetTime,
  GOSTDecrypt,
  GOSTEncrypt,
  GOSTHash,
  GOSTKeyUnwrap,
  GOSTKeyWrap,
  GOSTSign,
  GOSTVerify,
  GroupIPAddresses,
  Gunzip,
  Gzip,
  HammingDistance,
  HAS160,
  HASSHClientFingerprint,
  HASSHServerFingerprint,
  HaversineDistance,
  Head,
  HeatmapChart,
  HexDensityChart,
  HexToObjectIdentifier,
  HexToPEM,
  HMAC,
  HTMLToText,
  HTTPRequest,
  ImageBrightnessContrast,
  ImageFilter,
  ImageHueSaturationLightness,
  ImageOpacity,
  IndexOfCoincidence,
  InvertImage,
  IPv6TransitionAddresses,
  JA3Fingerprint,
  JA3SFingerprint,
  JA4Fingerprint,
  JA4ServerFingerprint,
  JavaScriptBeautify,
  JavaScriptMinify,
  JavaScriptParser,
  JPathExpression,
  Jq,
  JSONBeautify,
  JSONMinify,
  JSONToCSV,
  JSONtoYAML,
  Jump,
  JWKToPem,
  JWTDecode,
  JWTSign,
  JWTVerify,
  Keccak,
  Label,
  LevenshteinDistance,
  LMHash,
  Lorenz,
  LS47Decrypt,
  LS47Encrypt,
  LuhnChecksum,
  LZ4Compress,
  LZ4Decompress,
  LZMACompress,
  LZMADecompress,
  LZNT1Decompress,
  LZStringCompress,
  LZStringDecompress,
  Magic,
  MD2,
  MD4,
  MD5,
  MD6,
  Mean,
  Median,
  Merge,
  MicrosoftScriptDecoder,
  MIMEDecoding,
  MultipleBombe,
  Multiply,
  MurmurHash3,
  NormaliseImage,
  NormaliseUnicode,
  NOT,
  NTHash,
  Numberwang,
  ObjectIdentifierToHex,
  OffsetChecker,
  OpticalCharacterRecognition,
  OR,
  PadLines,
  ParseASN1HexString,
  ParseColourCode,
  ParseCSR,
  ParseDateTime,
  ParseIPRange,
  ParseIPv4Header,
  ParseIPv6Address,
  ParseObjectIDTimestamp,
  ParseQRCode,
  ParseSSHHostKey,
  ParseTCP,
  ParseTLSRecord,
  ParseTLV,
  ParseUDP,
  ParseUNIXFilePermissions,
  ParseURI,
  ParseUserAgent,
  ParseX509Certificate,
  ParseX509CRL,
  PEMToHex,
  PEMToJWK,
  PGPDecrypt,
  PGPDecryptAndVerify,
  PGPEncrypt,
  PGPEncryptAndSign,
  PGPVerify,
  PHPDeserialize,
  PHPSerialize,
  PlayMedia,
  PLISTViewer,
  PowerSet,
  ProtobufDecode,
  ProtobufEncode,
  PseudoRandomNumberGenerator,
  PubKeyFromCert,
  PubKeyFromPrivKey,
  Rabbit,
  RailFenceCipherDecode,
  RailFenceCipherEncode,
  RAKE,
  RandomizeColourPalette,
  RawDeflate,
  RawInflate,
  RC2Decrypt,
  RC2Encrypt,
  RC4,
  RC4Drop,
  Register,
  RegularExpression,
  RemoveDiacritics,
  RemoveEXIF,
  RemoveLineNumbers,
  RemoveNullBytes,
  RemoveWhitespace,
  RenderImage,
  RenderMarkdown,
  ResizeImage,
  Return,
  Reverse,
  RIPEMD,
  RisonDecode,
  RisonEncode,
  ROT13,
  ROT13BruteForce,
  ROT47,
  ROT47BruteForce,
  ROT8000,
  RotateImage,
  RotateLeft,
  RotateRight,
  RSADecrypt,
  RSAEncrypt,
  RSASign,
  RSAVerify,
  Salsa20,
  ScanForEmbeddedFiles,
  ScatterChart,
  Scrypt,
  SeriesChart,
  SetDifference,
  SetIntersection,
  SetUnion,
  SHA0,
  SHA1,
  SHA2,
  SHA3,
  Shake,
  SharpenImage,
  ShowBase64Offsets,
  ShowOnMap,
  Shuffle,
  SIGABA,
  Sleep,
  SM2Decrypt,
  SM2Encrypt,
  SM3,
  SM4Decrypt,
  SM4Encrypt,
  Snefru,
  Sort,
  Split,
  SplitColourChannels,
  SQLBeautify,
  SQLMinify,
  SSDEEP,
  StandardDeviation,
  Streebog,
  Strings,
  StripHTMLTags,
  StripHTTPHeaders,
  StripIPv4Header,
  StripTCPHeader,
  StripUDPHeader,
  SUB,
  Subsection,
  Substitute,
  Subtract,
  Sum,
  SwapCase,
  SwapEndianness,
  SymmetricDifference,
  SyntaxHighlighter,
  Tail,
  TakeBytes,
  TakeNthBytes,
  Tar,
  TCPIPChecksum,
  TextEncodingBruteForce,
  ToBase,
  ToBase32,
  ToBase45,
  ToBase58,
  ToBase62,
  ToBase64,
  ToBase85,
  ToBase92,
  ToBCD,
  ToBinary,
  ToBraille,
  ToCamelCase,
  ToCaseInsensitiveRegex,
  ToCharcode,
  ToDecimal,
  ToFloat,
  ToHex,
  ToHexContent,
  ToHexdump,
  ToHTMLEntity,
  ToKebabCase,
  ToLowerCase,
  ToMessagePack,
  ToModhex,
  ToMorseCode,
  ToOctal,
  ToPunycode,
  ToQuotedPrintable,
  ToSnakeCase,
  ToTable,
  ToUNIXTimestamp,
  ToUpperCase,
  TranslateDateTimeFormat,
  TripleDESDecrypt,
  TripleDESEncrypt,
  Typex,
  UnescapeString,
  UnescapeUnicodeCharacters,
  UnicodeTextFormat,
  Unique,
  UNIXTimestampToWindowsFiletime,
  Untar,
  Unzip,
  URLDecode,
  URLEncode,
  VarIntDecode,
  VarIntEncode,
  ViewBitPlane,
  VigenèreDecode,
  VigenèreEncode,
  Whirlpool,
  WindowsFiletimeToUNIXTimestamp,
  XKCDRandomNumber,
  XMLBeautify,
  XMLMinify,
  XOR,
  XORBruteForce,
  XPathExpression,
  XSalsa20,
  XXTEADecrypt,
  XXTEAEncrypt,
  YAMLToJSON,
  YARARules,
  Zip,
  ZlibDeflate,
  ZlibInflate,
};
(() => {
  window.addEventListener("DOMContentLoaded", () => {
    window.app = app;
    window.Buffer = Buffer;
    console.log(app)
    console.log(window)
  });
})();
